- name: install apache on web servers
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"

- name: ensure apache is running
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started

- name: change email for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin me2@here.now
  when: ansible_distribution == "Fedora"
  notify: restart_apache

- name: copy html file for site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
